### ISSUE TITLE
Lwt 4.0 compatibility

### ISSUE THREAD

**Issue by bikallem** [diml/lambda-term#60]
lambda term is not compatible with Lwt 4.0.0 and camomile 1.0.0. For lwt - the following issues need to be resolved.

1. Use of deprecated ```Lwt_sequence``` module with suitable doubly linked list?
2. Replace use of ```Lwt_logs``` with ```lwt_log``` or long-term with https://github.com/dbuenzli/logs.
3. ```Lwt_unix.execute_job``` to be replaced with ```Lwt_unix.run_job```

Camomile:
1. Repalce ```CamomileLibraryDyn.Camomile``` with ```CamomileLibraryDefault.Camomile```. This seems to make the build pass.

Is there any interest in updating ```lambda-term``` so that it is usable with ```lwt 4.0.0```. Most of these issues seem to be straightforward to do except ```Lwt_sequence``` issue. Maybe we could just copy the lwt deprecated ```Lwt_sequence``` here?

Note that since ```utop``` uses lambda-term, I believe the above changes are required if one is to use lwt 4.0.0 along with utop. 

I will send a [wip] pull request shortly.

**Comment by bikallem** [comment]
cc @diml @rgrinberg. Any ideas on how we can resolve ```Lwt_sequence``` issue? A quick one would be to just import the deprecated ```Lwt_sequence``` into lambda_term. Modulo that option, I am not aware of any suitable doubly linked list package.

**Comment by diml** [comment]
Thanks. Importing `Lwt_sequence` into lambda-term seems fine to me. For `Lwt_logs`, why not depend on the `lwt_log` package? That should be simpler.

**Comment by bikallem** [comment]
Ah, yes indeed.

**Comment by aantron** [comment]
See https://github.com/ocsigen/lwt/issues/573#issuecomment-380804023 about `Lwt_sequence`.

For `Lwt_log`, it is not absolutely necessary to replace it with `logs` to be compatible with 4.0.0. `Lwt_log` has been factored out into a separate library, so you only need to depend on `lwt_log`.

**Comment by aantron** [comment]
(it is encouraged to switch to a different logging library eventually, though, as we don't want to maintain Lwt_log)

**Comment by diml** [comment]
Noted for lwt_log. For `Lwt_sequence`, it is exposed in one module, but I don't expect that the functions referencing `Lwt_sequence` are used outside of lambda-term, so it shouldn't be a big deal if Lwt_sequence disappears from lwt entirely.

**Comment by aantron** [comment]
@bikallem Please take note of the comment from @diml. I think the Lwt 4.0.0 compatibility problem in Lambda-Term has been "over-diagnosed" both for `lwt_log` and for `Lwt_sequence`. Neither "breakage" is so hard that it requires what's been proposed so far.

As I mentioned in https://github.com/ocsigen/lwt/issues/573#issuecomment-380962771, Lambda-Term seems to have two different usages of `Lwt_sequence`. See the numbering there.

In the first one, Lambda-Term seems to use `Lwt_sequence` because it is a linked list, without using it to communicate with Lwt in any way. The "academically best" way to deal with this is to replace `Lwt_sequence` with any other linked list implementation, which should be fine if this is an internal API. The most "practical" may be to either do nothing, suppress the warning locally around some expressions or structure/signature items, or to add `-warn-error -3` to the right `jbuilder` files.

In the second one, Lambda-Term uses `Lwt_sequence` with `Lwt_main` in one file, `lTerm.ml`. For now, this can only be addressed by doing nothing, adding `-warn-error -3`, or doing something similar. On the Lwt end, we'll figure out how to replace `Lwt_sequence` in the `Lwt_main` API, and then you can get rid of this usage as well.

Note that the renaming of `lwt.log` to `lwt_log` makes Lambda-Term incompatible with Lwt 4.0.0, but deprecation of `Lwt_sequence` *does not*. The dev build of Lambda-Term may be broken (haven't tried it), because it passes `--dev` to Jbuilder, so presumably the dev build stops due to deprecation warnings. But release builds trigger the warnings and continue.

**Comment by aantron** [comment]
...and another of the longer-term ways to fix usage #1 would be to import `Lwt_sequence` into Lambda-Term and rename it, though the point of evicting it from Lwt is really to move it into a standard library, not into users. But given that usage #1 is not exposed in the API, and not related to usage #2 or Lwt, you don't need any type equalities or any compatibility between the imported copy of `Lwt_sequence` and the actual `Lwt_sequence` that is now in Lwt for #1.

I would try to avoid doing this, but I am suggesting it based on the attempt to import `Lwt_sequence` in the PR.

**Comment by aantron** [comment]
As for `lwt_log`, it will remain compatible with Lwt in the foreseeable future. We have no plans to do anything that will break it, and if we break it slightly, we will do some minimal maintenance on it. So, the best course of action is probably to simply keep using Lwt_log in its new packaging.

If we do something like give Lwt a fresh Unix API, then we won't port Lwt_log to that. If Lwt_log becomes actually incompatible with Lwt, we will constrain `lwt_log`, so users that depend on it will be implicitly held back.

**Comment by bikallem** [comment]
@aantron > ...and another of the longer-term ways to fix usage 1 would be to import Lwt_sequence into Lambda-Term and rename it, though the point of evicting it from Lwt is really to move it into a standard library, not into users. But given that usage 1 is not exposed in the API, and not related to usage 2 or Lwt, you don't need any type equalities or any compatibility between the imported copy of Lwt_sequence and the actual Lwt_sequence that is now in Lwt for 1.

Indeed the attempt was to address it - if possible - in the longer term. So I tried the exact approach you suggested, i.e. importing and renaming in ```lambda-term```. However, since lambda-term is using the api ```Lwt_main.enter_iter_hooks``` - see https://github.com/diml/lambda-term/blob/master/src/lTerm.ml#L115 - I think we need to establish the type equality between the two ```Lwt_sequence```, i.e. the imported one and the one exposed by ```lwt 4.0.0```. I did raise this finding/issue here https://github.com/ocsigen/lwt/issues/573#issuecomment-380847926. 

My first instinct was as you observed. Maybe this is 'over-thinking'. Why don't I just silence those deprecation warnings - locally and/or in expresssions - and be done with it? However, I wanted to explore a longer-term approach so that we don't revisit this issue again when ```Lwt_sequence``` is eventually removed from ```lwt``. 

But anyway, I agree with you now. This is over-diagnosed at this point. I will go with the straightforward approach. Hopefully that will make utop/lambda-term compatible with lwt 4.0.0.

**Comment by aantron** [comment]
@bikallem Agreeing with most of the above, I want to point out that I'm saying that most of the usage of `Lwt_sequence` in Lambda-Term doesn't seem to be related to `Lwt_main`, which means you could, in principle, import `Lwt_sequence`, or do anything else to address it, and separately address `lTerm.ml` by suppressing a deprecation warning and/or waiting for me to get it together on the Lwt end by tweaking `Lwt_main` a bit :)

Again, the usage in `lTerm.ml` is completely unrelated, AFAICT, to any of the other usages of `Lwt_sequence` in Lambda-Term. You could refactor `lTerm.ml` without touching the other usage, and you could refactor the other usage without touching `lTerm.ml`. The `lTerm.ml` usage depends on the interaction between `Lwt_sequence` and `Lwt_main`, but the other usage only depends on the existence of `Lwt_sequence`.

Looking at how `lTerm.ml` uses `Lwt_sequence`, which is just as a way to add callbacks, not as a linked list, it doesn't seem that you'd want to import `Lwt_sequence` for that specific usage anyway. It is the other, unrelated usage of `Lwt_sequence` that (barely) needs it to be a linked list, so that's the stimulus for importing it in the first place. So, the importation of `Lwt_sequence` is not connected with `Lwt_main` at all through the code of Lambda-Term. It may be in some other projects, where `Lwt_sequence` is first forced by (1) usage of `Lwt_main` (2) additional code interacting with that usage also through `Lwt_sequence` (3) optionally, `Lwt_sequence` being exposed in the user project's API, but Lambda-Term doesn't have (2) or (3).

**Comment by aantron** [comment]
In particular, you don't need type equality because the usage that makes `Lwt_sequence` worth importing, does not interact with the usage that communicates with Lwt.

**Comment by aantron** [comment]
Or, in other words, since the two usages are independent, you don't need to replace `Lwt_sequence` in the same way in `lTerm.ml` vs. the rest of where it is used in Lambda-Term.

The fact that they both use `Lwt_sequence` is an accident (because the non-`lTerm.ml` usages relying on `Lwt_sequence` are an accident not forced by Lwt), and it's not necessary to rigidly preserve that accident by ensuring equality between the types.

**Comment by bikallem** [comment]
Ah. okay. Thanks for the clarification. :+1:

**Comment by tuncer** [comment]
Since #63 has been merged and lambda-term 1.13 is on its way to opam (https://github.com/ocaml/opam-repository/pull/12099), this should be resolved.
